<a href="https://colab.research.google.com/github/RoginRobert2014/CE888/blob/main/lab4/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=3)


In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv", header=None)
jokes_data = data.copy()
len(jokes_data)

24983

In [ ]:
# Quiz question 4
jokes_data.loc[[9146]]

0     1     2     3     4     5    ...   95    96    97    98   99    100
9146  100  8.69  0.19  4.85  0.78 -0.97  ...  4.61  5.19  1.07 -1.65  5.0 -8.64

[1 rows x 101 columns]

In [ ]:
# Replace the value 99 with NaNs . This is the test set.
jokes_test_data = jokes_data.replace(99.00,np.nan)
jokes_test_data.head()


0     1     2     3     4     5    ...   95    96    97    98    99    100
0   74.0 -7.82  8.79 -9.66 -8.16 -7.52  ...   NaN   NaN -5.63   NaN   NaN   NaN
1  100.0  4.08 -0.29  6.36  4.37 -2.38  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2   49.0   NaN   NaN   NaN   NaN  9.03  ...   NaN   NaN   NaN   NaN   NaN   NaN
3   48.0   NaN  8.35   NaN   NaN  1.80  ...   NaN   NaN   NaN   NaN   NaN   NaN
4   91.0  8.50  4.61 -4.17 -5.39  1.36  ...  5.73  1.55  3.11  6.55  1.80  1.60

[5 rows x 101 columns]

In [ ]:
# Remove the column because it doesn't contain ratings
jokes_test_data = jokes_test_data.drop(jokes_test_data.columns[0], axis=1)
jokes_test_data_org = jokes_test_data.copy()
jokes_test_data.head()

1     2     3     4     5     6    ...   95    96    97    98    99    100
0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1  4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2   NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3   NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4  8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60

[5 rows x 100 columns]

In [ ]:
# Question 4

jokes_test_data_value = jokes_data.loc[jokes_data[0]==9146]
jokes_test_data_value

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 101 columns]

In [ ]:
# Use pandas to find the best- and the worst-rated jokes
mean_array = []
for i in jokes_test_data.columns:
  mean_array.append(np.mean(jokes_test_data[i]))
print(mean_array)
print(len(mean_array))
best_joke = max(mean_array)

# Answer to Quiz 3 also
print("Best joke is in column is " , np.argmax(mean_array)  , "with a value ", best_joke)
worst_joke = min(mean_array)
print("Worst joke is in column is in ", np.argmin(mean_array)  , "with a value ", worst_joke)


[0.9045733041575473, 0.20845963484381844, 0.31657433000841273, -1.4491139159405428, 0.4035564719541942, 1.5944471636238982, -0.42966247597693813, -0.6240851046795616, -0.5570308532249889, 1.3012305648494402, 1.8057967095916765, 1.4492900147170251, -1.762881790160528, 1.3963344437042027, -1.7062013052007865, -3.104818018018001, -1.1151413130504473, -0.6351034869290236, 0.15422691968932692, -0.933996797437956, 2.095625777456765, 0.8686618765455205, 0.1091923326511263, -1.6874198627117565, 0.38237269408147534, 1.286232000000005, 3.1898213138451355, 1.5188299291371237, 2.972455281944338, -0.43649274072426036, 2.198943462037635, 3.155987654320997, -1.3686476293103353, 0.8594940407178956, 3.00635059313884, 3.3125003004205738, -1.3639867306439248, 1.3004786070522285, 1.0673370883882167, 0.998634699526747, -0.3204998135024238, 1.966875330701282, -0.9248558049226209, -2.1118909562959822, 1.1086161781946084, 1.5002315343915265, 1.5595346432264716, 1.825884443008845, 2.7712978322714887, 3.6650848

In [ ]:
array = jokes_test_data.values

In [ ]:
# validation set

def replaceFn(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(array!=np.nan) 
  n_rated = len(rated[1])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

new_arr, idx = replaceFn(array, 0.1)
print(new_arr)
print(idx)

[[-7.82  8.79 99.   ...   nan   nan   nan]
 [ 4.08 -0.29  6.36 ... 99.   99.    1.07]
 [  nan 99.     nan ...   nan   nan   nan]
 ...
 [  nan   nan 99.   ...   nan   nan   nan]
 [  nan   nan   nan ...   nan   nan   nan]
 [ 2.43  2.67 -3.98 ...   nan   nan   nan]]
(array([13187, 12432,  9338, ...,  5635,  8706, 16505]), array([36, 73, 46, ..., 28, 92, 78]))


In [ ]:
print("new_arr", new_arr)
print("idx", idx)

new_arr [[-7.82  8.79 99.   ...   nan   nan   nan]
 [ 4.08 -0.29  6.36 ... 99.   99.    1.07]
 [  nan 99.     nan ...   nan   nan   nan]
 ...
 [  nan   nan 99.   ...   nan   nan   nan]
 [  nan   nan   nan ...   nan   nan   nan]
 [ 2.43  2.67 -3.98 ...   nan   nan   nan]]
idx (array([13187, 12432,  9338, ...,  5635,  8706, 16505]), array([36, 73, 46, ..., 28, 92, 78]))


In [ ]:
n_latent_factors = 2

user_ratings = jokes_test_data.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))


In [ ]:
latent_user_preferences

array([[0.404, 0.008],
       [0.222, 0.875],
       [0.524, 0.017],
       ...,
       [0.437, 0.658],
       [0.29 , 0.505],
       [0.464, 0.439]])

In [ ]:
latent_item_features

array([[0.951, 0.683],
       [0.227, 0.081],
       [0.513, 0.691],
       [0.232, 0.739],
       [0.331, 0.554],
       [0.385, 0.658],
       [0.703, 0.03 ],
       [0.553, 0.56 ],
       [0.539, 0.474],
       [0.893, 0.311],
       [0.306, 0.079],
       [0.646, 0.896],
       [0.081, 0.526],
       [0.605, 0.534],
       [0.419, 0.942],
       [0.609, 0.756],
       [0.83 , 0.39 ],
       [0.913, 0.924],
       [0.299, 0.599],
       [0.347, 0.055],
       [0.936, 0.408],
       [0.359, 0.781],
       [0.956, 0.742],
       [0.92 , 0.117],
       [0.996, 0.974],
       [0.256, 0.934],
       [0.282, 0.578],
       [0.194, 0.143],
       [0.038, 0.021],
       [0.221, 0.273],
       [0.97 , 0.249],
       [0.641, 0.943],
       [0.434, 0.318],
       [0.314, 0.103],
       [0.748, 0.884],
       [0.335, 0.227],
       [0.979, 0.342],
       [0.849, 0.835],
       [0.739, 0.141],
       [0.799, 0.309],
       [0.266, 0.037],
       [0.172, 0.265],
       [0.809, 0.124],
       [0.4

In [ ]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [ ]:
num_iter = 10
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
plt.figure()
plt.plot(np.arange(0, num_iter, 10000), hist)
plt.xlabel("Iterations")
plt.ylabel("MSE")
plt.show()

Iteration 0/10:	MSE=26.120367


In [ ]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[0.705, 0.541, 0.51 , ..., 0.836, 0.282, 1.079],
       [1.002, 0.498, 0.56 , ..., 1.121, 0.604, 1.509],
       [1.617, 1.189, 1.138, ..., 1.905, 0.686, 2.472],
       ...,
       [0.954, 0.565, 0.588, ..., 1.09 , 0.507, 1.445],
       [0.901, 0.529, 0.553, ..., 1.028, 0.482, 1.365],
       [1.563, 1.028, 1.026, ..., 1.811, 0.755, 2.378]])

In [ ]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
data = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv")
comparison_data.columns = data.values

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv")
data

74  -7.82   8.79  -9.66  -8.16  ...  99.22  -5.63  99.23  99.24  99.25
0      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
1       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
2       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
4      100  -6.17  -3.54   0.44  -8.50  ...  -3.35   0.05  -9.08  -5.05  -3.45
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24977  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24978   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24979   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24980   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24982 rows x 101 columns]

In [ ]:
# Quiz
import pandas as pd

items_df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/CE888/labs/lab4/movies_latent_factors.xlsx', sheet_name='Items')
user_df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/CE888/labs/lab4/movies_latent_factors.xlsx', sheet_name='Users')

In [ ]:
# Question 6

movie_items_high = items_df['Factor15'].max()
movie_items[items_df['Factor15'] == items_df['Factor15'].max()]

Movie ID                       Title  ...  Factor14  Factor15
51       604  The Matrix Reloaded (2003)  ...  0.748458  2.120907

[1 rows x 17 columns]

In [ ]:
movie_items_value = items_df.loc[items_df['Movie ID']==462]
movie_items_value

Movie ID                   Title   Factor1  ...  Factor13  Factor14  Factor15
40       462  Erin Brockovich (2000)  0.824202  ...  -0.13041 -0.146135  0.113734

[1 rows x 17 columns]

In [ ]:
# Question 5

movie_items_value = user_df.loc[user_df['User']==3806]
movie_items_value

User   Factor1   Factor2  Factor3  ...  Factor12  Factor13  Factor14  Factor15
12  3806 -0.042344 -0.040755 -0.05572  ... -0.040915 -0.130308 -0.021816  0.034549

[1 rows x 16 columns]

In [ ]:
user_df.set_index('User', inplace=True)

In [ ]:
items_df.set_index('Movie ID', inplace=True)

In [ ]:
items_data = items_df.drop('Title', axis=1).values

In [ ]:
user_data = user_df.values

In [ ]:
def Predict_Rating(user_ID, movie_ID):
  user_list = df_users.loc[user_ID].values
  movie_list = df_items.loc[movie_ID].drop('Title').values
  return user_list.dot(movie_list)

In [ ]:
# Question 7
Predict_Rating(3878, 122)

-1.9801680405720616

In [ ]:
# Question 8
Predict_Rating(525, 664)

-0.03828289238310254